### ISSUE TITLE
In fact, its not working

### ISSUE THREAD

**Issue by mannro** [GitGangGuy/serverless-sapper-edge#4]
I'm change `sapper` to `test123sapper` in serverless.yml
`serverless deploy` returns

```
> Finished in 25.7s. Type node __sapper__/build to run the app.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Updated Lambda assume role policy to allow Lambda@Edge to assume the role
Serverless: Added "origin-request" Lambda@Edge association for version "SsrLambdaVersionbdi49375m3bGcke2p5Co8geDEtmRe3DrYHcJPbNapE" to distribution "test123sapperEdgeDistribution"
Running command: aws s3 cp --recursive ./__sapper__/build/client/ s3://test123sapper-edge-bucket/client/ --cache-control "max-age=31536000,public,immutable"
upload failed: __sapper__/build/client/about.9e41247b.js to s3://test123sapper-edge-bucket/client/about.9e41247b.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/[slug].74ad11f5.css to s3://test123sapper-edge-bucket/client/[slug].74ad11f5.css An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/[slug].74ad11f5.js to s3://test123sapper-edge-bucket/client/[slug].74ad11f5.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/client.da0dcb33.js to s3://test123sapper-edge-bucket/client/client.da0dcb33.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/index.4335f39a.css to s3://test123sapper-edge-bucket/client/index.4335f39a.css An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/index.4335f39a.js to s3://test123sapper-edge-bucket/client/index.4335f39a.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/client.da0dcb33.css to s3://test123sapper-edge-bucket/client/client.da0dcb33.css An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/client.d755e539.js to s3://test123sapper-edge-bucket/client/client.d755e539.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/index.7d9a0c9e.js to s3://test123sapper-edge-bucket/client/index.7d9a0c9e.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/index.7d9a0c9e.css to s3://test123sapper-edge-bucket/client/index.7d9a0c9e.css An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/legacy/[slug].93819d47.css to s3://test123sapper-edge-bucket/client/legacy/[slug].93819d47.css An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/legacy/[slug].93819d47.js to s3://test123sapper-edge-bucket/client/legacy/[slug].93819d47.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/legacy/about.2bcfd7e6.js to s3://test123sapper-edge-bucket/client/legacy/about.2bcfd7e6.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/legacy/client.1866cff4.css to s3://test123sapper-edge-bucket/client/legacy/client.1866cff4.css An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/legacy/client.21c179fa.js to s3://test123sapper-edge-bucket/client/legacy/client.21c179fa.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/legacy/index.5d51dbf5.css to s3://test123sapper-edge-bucket/client/legacy/index.5d51dbf5.css An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/legacy/index.2b632565.css to s3://test123sapper-edge-bucket/client/legacy/index.2b632565.css An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/legacy/index.2b632565.js to s3://test123sapper-edge-bucket/client/legacy/index.2b632565.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/legacy/index.5d51dbf5.js to s3://test123sapper-edge-bucket/client/legacy/index.5d51dbf5.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/legacy/client.1866cff4.js to s3://test123sapper-edge-bucket/client/legacy/client.1866cff4.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/legacy/main.850609924.css to s3://test123sapper-edge-bucket/client/legacy/main.850609924.css An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/main.850609924.css to s3://test123sapper-edge-bucket/client/main.850609924.css An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
upload failed: __sapper__/build/client/shimport@1.0.1.js to s3://test123sapper-edge-bucket/client/shimport@1.0.1.js An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist

  Error --------------------------------------------------

  Error: Command failed: aws s3 cp --recursive ./__sapper__/build/client/ s3://test123sapper-edge-bucket/client/ --cache-control "max-age=31536000,public,immutable"
      at checkExecSyncError (child_process.js:616:11)
      at execSync (child_process.js:652:15)
      at Scriptable.runCommand (/mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/index.js:48:12)
      at /mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/index.js:41:21
      at tryCatcher (/mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/node_modules/bluebird/js/release/reduce.js:166:18)
      at Object.gotAccum (/mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/mnt/c/Users/kis/data/temp/t/serverless-sapper-edge/node_modules/serverless-scriptable-plugin/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.10.0
     Framework Version:         2.0.0
     Plugin Version:            4.0.2
     SDK Version:               2.3.2
     Components Version:        3.1.3
```

so i create bucket named `test123sapper-edge-bucket`
`serverless deploy` now returns

```
> Finished in 26.5s. Type node __sapper__/build to run the app.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Updated Lambda assume role policy to allow Lambda@Edge to assume the role
Serverless: Added "origin-request" Lambda@Edge association for version "SsrLambdaVersionfxh1cNNhkPHVeVOOyZuyBhMLQKJBzcx0rtfPac7g" to distribution "test123sapperEdgeDistribution"
Running command: aws s3 cp --recursive ./__sapper__/build/client/ s3://test123sapper-edge-bucket/client/ --cache-control "max-age=31536000,public,immutable"
upload: __sapper__/build/client/[slug].74ad11f5.js to s3://test123sapper-edge-bucket/client/[slug].74ad11f5.js
upload: __sapper__/build/client/client.d755e539.js to s3://test123sapper-edge-bucket/client/client.d755e539.js
upload: __sapper__/build/client/client.da0dcb33.css to s3://test123sapper-edge-bucket/client/client.da0dcb33.css
upload: __sapper__/build/client/index.4335f39a.css to s3://test123sapper-edge-bucket/client/index.4335f39a.css
upload: __sapper__/build/client/index.7d9a0c9e.css to s3://test123sapper-edge-bucket/client/index.7d9a0c9e.css
upload: __sapper__/build/client/index.4335f39a.js to s3://test123sapper-edge-bucket/client/index.4335f39a.js
upload: __sapper__/build/client/client.da0dcb33.js to s3://test123sapper-edge-bucket/client/client.da0dcb33.js
upload: __sapper__/build/client/index.7d9a0c9e.js to s3://test123sapper-edge-bucket/client/index.7d9a0c9e.js
upload: __sapper__/build/client/[slug].74ad11f5.css to s3://test123sapper-edge-bucket/client/[slug].74ad11f5.css
upload: __sapper__/build/client/legacy/[slug].93819d47.css to s3://test123sapper-edge-bucket/client/legacy/[slug].93819d47.css
upload: __sapper__/build/client/about.9e41247b.js to s3://test123sapper-edge-bucket/client/about.9e41247b.js
upload: __sapper__/build/client/legacy/client.1866cff4.css to s3://test123sapper-edge-bucket/client/legacy/client.1866cff4.css
upload: __sapper__/build/client/legacy/client.21c179fa.js to s3://test123sapper-edge-bucket/client/legacy/client.21c179fa.js
upload: __sapper__/build/client/legacy/[slug].93819d47.js to s3://test123sapper-edge-bucket/client/legacy/[slug].93819d47.js
upload: __sapper__/build/client/legacy/index.2b632565.js to s3://test123sapper-edge-bucket/client/legacy/index.2b632565.js
upload: __sapper__/build/client/legacy/client.1866cff4.js to s3://test123sapper-edge-bucket/client/legacy/client.1866cff4.js
upload: __sapper__/build/client/legacy/index.5d51dbf5.css to s3://test123sapper-edge-bucket/client/legacy/index.5d51dbf5.css
upload: __sapper__/build/client/legacy/index.5d51dbf5.js to s3://test123sapper-edge-bucket/client/legacy/index.5d51dbf5.js
upload: __sapper__/build/client/legacy/main.850609924.css to s3://test123sapper-edge-bucket/client/legacy/main.850609924.css
upload: __sapper__/build/client/legacy/index.2b632565.css to s3://test123sapper-edge-bucket/client/legacy/index.2b632565.css
upload: __sapper__/build/client/legacy/about.2bcfd7e6.js to s3://test123sapper-edge-bucket/client/legacy/about.2bcfd7e6.js
upload: __sapper__/build/client/main.850609924.css to s3://test123sapper-edge-bucket/client/main.850609924.css
upload: __sapper__/build/client/shimport@1.0.1.js to s3://test123sapper-edge-bucket/client/shimport@1.0.1.js
Running command: aws s3 cp --recursive ./static/ s3://test123sapper-edge-bucket/static/ --cache-control "max-age=31536000,public,immutable"
upload: static/favicon.png to s3://test123sapper-edge-bucket/static/favicon.png
upload: static/global.css to s3://test123sapper-edge-bucket/static/global.css
upload: static/logo-192.png to s3://test123sapper-edge-bucket/static/logo-192.png
upload: static/manifest.json to s3://test123sapper-edge-bucket/static/manifest.json
upload: static/logo-512.png to s3://test123sapper-edge-bucket/static/logo-512.png
upload: static/great-success.png to s3://test123sapper-edge-bucket/static/great-success.png
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service ssr.zip file to S3 (641.52 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
............
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A560370823851%3Astack%2Ftest123sapperEdge-dev%2Ff08f2ad0-f809-11ea-abee-0ea47a628cf7

  Serverless Error ---------------------------------------

  An error occurred: test123sapperEdgeBucket - test123sapper-edge-bucket already exists.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.10.0
     Framework Version:         2.0.0
     Plugin Version:            4.0.2
     SDK Version:               2.3.2
     Components Version:        3.1.3
```

what's wrong?

**Comment by GitGangGuy** [comment]
I'm sorry, but this repository isn't being maintained any more. If you're interested, you can go through the `serverless.yml` file yourself and try fixing it. I'll go ahead and archive it.
